services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html


  php-fpm:
    build:
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html


  postgres:
    image: postgres:13.1
#    volumes:
#      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - 54321:5432

